import type {NextPage} from 'next'
import Head from 'next/head'
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Allora E-Commerce</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>You are Home page...</h1>
            <br/>

            <Link href={'/auth/signin'}> login </Link>
            <br/>

            <Link href={'/auth/signup'}>register</Link>
            <br/>

            <Link href={'/profile'}>profile (protected)</Link>
            <br/>

        </div>
    )
}
export default Home;
