export const ActionTypes: any = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REGISTER:"REGISTER",
    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    USER_VERIFY_TOKEN:"USER_VERIFY_TOKEN"
}